<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VSULTANOV-L01" failures="2" tests="6" name="Surefire test" time="6.789" errors="0" timestamp="2024-05-14T14:17:02 UZT">
  <testcase classname="tests.DDTests" name="testPOSTUser" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.RuntimeException: java.io.FileNotFoundException: D:\0.Practice\Automation_API2\API_Testing\testData\Data.xlsx (Системе не удается найти указанный путь)">
      <![CDATA[java.lang.RuntimeException: java.lang.RuntimeException: java.io.FileNotFoundException: D:\0.Practice\Automation_API2\API_Testing\testData\Data.xlsx (Системе не удается найти указанный путь)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: D:\0.Practice\Automation_API2\API_Testing\testData\Data.xlsx (Системе не удается найти указанный путь)
at utilities.DataProviders.getAllData(DataProviders.java:31)
... 30 more
Caused by: java.io.FileNotFoundException: D:\0.Practice\Automation_API2\API_Testing\testData\Data.xlsx (Системе не удается найти указанный путь)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at utilities.XLUtility.getRowCount(XLUtility.java:29)
at utilities.DataProviders.getAllData(DataProviders.java:19)
... 35 more
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- testPOSTUser -->
  <testcase classname="tests.DDTests" name="deleteUserByName" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.RuntimeException: java.io.FileNotFoundException: D:\0.Practice\Automation_API2\API_Testing\testData\Data.xlsx (Системе не удается найти указанный путь)">
      <![CDATA[java.lang.RuntimeException: java.lang.RuntimeException: java.io.FileNotFoundException: D:\0.Practice\Automation_API2\API_Testing\testData\Data.xlsx (Системе не удается найти указанный путь)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: D:\0.Practice\Automation_API2\API_Testing\testData\Data.xlsx (Системе не удается найти указанный путь)
at utilities.DataProviders.getUserNames(DataProviders.java:54)
... 30 more
Caused by: java.io.FileNotFoundException: D:\0.Practice\Automation_API2\API_Testing\testData\Data.xlsx (Системе не удается найти указанный путь)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at utilities.XLUtility.getRowCount(XLUtility.java:29)
at utilities.DataProviders.getUserNames(DataProviders.java:45)
... 35 more
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- deleteUserByName -->
  <testcase classname="tests.UserTests" name="testPOSTuser" time="2.497"/>
  <testcase classname="tests.UserTests" name="testGetUserByName" time="0.952"/>
  <testcase classname="tests.UserTests" name="updateUserByName" time="1.862"/>
  <testcase classname="tests.UserTests" name="testDeleteUserByName" time="0.932"/>
</testsuite> <!-- Surefire test -->
